# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A mean function using Rcpp
#' @description A mean function using Rcpp
#' @param x the vector to get the mean 
#' @return the mean of x
#' @examples
#' \dontrun{
#' meanC(c(1,2,3))
#' }
#' @export
meanC <- function(x) {
    .Call(`_SC19036_meanC`, x)
}

